import {writeFile} from 'node:fs/promises';
import {pilotRegions} from './regions.mjs';
let sequence=0;
const palette={1:'#849967',2:'#a6c97a',3:'#c6f36b'};
function map(view,intensity,full=false){
 const id=`anatomy-${++sequence}`;
 const crop=full?'0 0 960 1920':'190 245 580 590';
 const image=`<rect width="960" height="1920" filter="url(#${id}-base)"/>`;
 const paths=Object.entries(intensity).flatMap(([head,level])=>(pilotRegions[head]||[]).filter(p=>p.view===view).map(p=>`<path d="${p.d}" fill="${palette[level]}"/>`)).join('');
 return `<svg role="img" aria-label="${view} anatomy with ${Object.keys(intensity).join(', ')} highlighted" viewBox="${crop}" preserveAspectRatio="xMidYMid meet" style="isolation:isolate"><defs><filter id="${id}-base" x="0" y="0" width="960" height="1920" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feImage href="../../../public/muscle-maps/${view}.webp" x="0" y="0" width="960" height="1920" preserveAspectRatio="xMidYMid meet"/></filter><mask id="${id}" maskUnits="userSpaceOnUse" x="0" y="0" width="960" height="1920" style="mask-type:luminance">${image}</mask></defs><rect width="960" height="1920" fill="#101414"/>${image}<g mask="url(#${id})" style="mix-blend-mode:multiply">${paths}</g></svg>`;
}
const chest={'chest-upper':3,'chest-middle':3,'chest-lower':3};
const back={'back-traps':3,'back-mid':3,'back-lats':3,'back-lower':3};
const shoulder={'delts-front':3,'delts-side':3,'delts-rear':3};
const card=(name,view,heads)=>`<article><div class="card-map">${map(view,heads)}</div><h3>${name}</h3><p>Muscle group</p></article>`;
const row=(name,view,heads,label)=>`<article class="row"><div class="thumb">${map(view,heads)}</div><div><h3>${name}</h3><p>${label}</p><span class="badge">Primary</span> <span class="secondary">Secondary</span></div></article>`;
await writeFile(new URL('./preview.html',import.meta.url),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spec 19 — anatomical map pilots</title><style>*{box-sizing:border-box}body{margin:0;background:#101414;color:#f4f7f5;font:1rem/1.5 Arial,sans-serif}main{max-width:1100px;margin:auto;padding:24px 16px}h1{font-size:1.75rem;line-height:1.2}h2{font-size:1.25rem;margin:28px 0 12px}h3{font-size:1.125rem;margin:10px 0 4px;overflow-wrap:anywhere}p{color:#afbeb5;margin:6px 0}a{color:#c6f36b}.columns{display:grid;grid-template-columns:420px 1fr;gap:32px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:12px}article{padding:16px;background:#1a2020;border:1px solid #3a4843;border-radius:16px;min-width:0}.card-map{height:120px}svg{width:100%;height:100%;display:block}.row{display:flex;align-items:center;gap:16px;margin:12px 0}.thumb{width:80px;height:104px;flex:none}.row>div:last-child{min-width:0}.badge,.secondary{font-size:.875rem}.badge{color:#c6f36b}.secondary{color:#afbeb5}.full{display:flex;max-width:320px;margin:auto}.full svg{width:50%;height:auto}.reference{max-width:250px;width:100%;height:auto;display:block;margin:16px auto}.notice{border-left:3px solid #c6f36b;padding-left:12px}.small{font-size:.875rem}@media(max-width:760px){.columns{display:block}main{padding:16px}.row{gap:12px;padding:12px}.thumb{width:80px}}</style><main><h1>Detailed muscle-map pilots</h1><p class="notice">Spec 19 review: chest, back and shoulders. Highlights below are live SVG regions over two shared neutral images.</p><p><a href="before.html">Compare existing maps</a></p><div class="columns"><section><h2>Exercise menu · 120 px artwork</h2><div class="cards">${card('Chest','front',chest)}${card('Back','back',back)}${card('Shoulders · front','front',shoulder)}${card('Shoulders · rear','back',shoulder)}</div><h2>Exercise rows · 80 × 104 px</h2>${row('Barbell Bench Press','front',{'chest-middle':3,'chest-upper':1,'chest-lower':1,'delts-front':1},'Mid chest · upper/lower chest and front delts')}${row('Incline Dumbbell Press','front',{'chest-upper':3,'chest-middle':1,'delts-front':1},'Upper chest · mid chest and front delts')}${row('Lat Pulldown','back',{'back-lats':3,'back-mid':1},'Lats · mid back')}<p class="small">Pilot rows isolate the regions being reviewed. Arm and lower-body regions follow after approval; these are not the complete production exercise maps.</p></section><section><h2>Full-map proportions</h2><div class="full">${map('front',chest,true)}${map('back',back,true)}</div><p class="small">Lime: primary/high. Olive: secondary/low. Neutral regions keep their anatomical shading.</p><h2>Approved movement-guide reference</h2><img class="reference" src="../../../public/exercise-demos/cable-curl.webp" width="960" height="1200" alt="Approved Cable Curl anatomical movement guide"><p class="small">The existing movement artwork remains unchanged.</p></section></div></main></html>`);


