import type { ExerciseId } from "./catalog.ts";

type ExerciseDemo = {
  alt: string;
  secondPosition: string;
  setup: string;
  movement: string;
};

export const EXERCISE_DEMOS: Record<ExerciseId, ExerciseDemo> = {
  "barbell-bench-press": { alt: "Lifter on a flat bench holding a barbell above the chest, then lowering it toward the chest.", secondPosition: "Lowered", setup: "Lie on a flat bench with feet planted and hands wider than shoulder width on the bar.", movement: "Lower the bar toward your mid chest, then press it back above your shoulders." },
  "incline-bench-press": { alt: "Lifter on an inclined bench with a barbell above the upper chest, then lowered toward it.", secondPosition: "Lowered", setup: "Sit against an inclined bench with feet planted and hands wider than your shoulders on the bar.", movement: "Lower the bar toward your upper chest, then press it back up with control." },
  "incline-dumbbell-press": { alt: "Lifter on an inclined bench holding two dumbbells above the chest, then at chest level.", secondPosition: "Lowered", setup: "Lean against an inclined bench with a dumbbell in each hand above your upper chest.", movement: "Bend your elbows to lower both weights beside your chest, then press them up." },
  "machine-chest-press": { alt: "Seated lifter holding chest-press machine handles near the chest, then pushing them forward.", secondPosition: "Pressed", setup: "Sit against the machine backrest with feet planted and handles near chest height.", movement: "Press the handles forward, then let them return toward your chest under control." },
  "wide-chest-press": { alt: "Seated lifter on a wide-grip chest-press machine with handles beside the chest, then pushed forward.", secondPosition: "Pressed", setup: "Sit against the back pad and take the machine's wide handles at chest height.", movement: "Push the handles forward, then bring them back slowly to the start." },
  "pec-deck": { alt: "Seated lifter on a pec-deck machine with arms open, then drawing the handles together in front.", secondPosition: "Closed", setup: "Sit against the pec-deck backrest with forearms or hands on its pads or handles.", movement: "Bring your arms together in front of your chest, then reopen them with control." },
  "cable-crossover": { alt: "Lifter between two high cable pulleys with arms spread, then drawing the handles down and together.", secondPosition: "Crossed", setup: "Stand between high cable pulleys with a handle in each hand and a staggered stance.", movement: "Draw the handles down and together in front of your torso, then reopen your arms slowly." },

  "lat-pulldown": { alt: "Seated lifter holding an overhead cable bar with arms extended, then pulling it toward the upper chest.", secondPosition: "Pulled", setup: "Sit under the pulldown bar with thighs secured and hands outside shoulder width.", movement: "Pull the bar toward your upper chest, then let it rise until your arms extend again." },
  "seated-cable-row": { alt: "Seated lifter with feet braced, holding a cable handle at arm's length, then at the torso.", secondPosition: "Pulled", setup: "Sit facing the low cable with feet braced and arms reaching toward the handle.", movement: "Pull the handle toward your lower ribs, then extend your arms forward with control." },
  "barbell-row": { alt: "Lifter hinged at the hips holding a barbell below the torso, then pulling it toward the lower ribs.", secondPosition: "Pulled", setup: "Stand over a barbell, hinge at your hips, and hold the bar with arms hanging below you.", movement: "Row the bar toward your lower ribs, then lower it while keeping your torso steady." },
  "one-arm-dumbbell-row": { alt: "Lifter braced on a bench with one hand, holding a dumbbell down, then rowing it toward the hip.", secondPosition: "Pulled", setup: "Brace one hand and knee on a bench and hold a dumbbell below the opposite shoulder.", movement: "Pull the dumbbell toward your hip, then lower it until your arm extends." },
  "straight-arm-pulldown": { alt: "Standing lifter holding a high cable bar with straight arms forward, then drawing it down toward the thighs.", secondPosition: "Lowered", setup: "Face a high cable pulley and hold its bar with arms nearly straight in front of you.", movement: "Pull the bar down toward your thighs without bending your elbows much, then raise it slowly." },
  "dumbbell-shrug": { alt: "Standing lifter holding dumbbells at the sides with shoulders relaxed, then raised toward the ears.", secondPosition: "Raised", setup: "Stand upright with a dumbbell in each hand at your sides.", movement: "Lift your shoulders upward, then lower them fully without swinging the weights." },
  "back-extension": { alt: "Lifter supported at the hips on a back-extension bench with torso lowered, then lifted into line with the legs.", secondPosition: "Raised", setup: "Place your hips on the back-extension pad and secure your feet under its supports.", movement: "Raise your torso until it lines up with your legs, then fold forward at the hips again." },

  "overhead-press": { alt: "Standing lifter holding a barbell at the upper chest, then pressing it overhead.", secondPosition: "Pressed", setup: "Stand with feet planted and hold the barbell at your upper chest.", movement: "Press the bar overhead, then lower it to your upper chest with control." },
  "dumbbell-shoulder-press": { alt: "Seated lifter with dumbbells beside the shoulders, then pressing both overhead.", secondPosition: "Pressed", setup: "Sit against a bench backrest with a dumbbell beside each shoulder.", movement: "Press both weights overhead, then lower them beside your shoulders." },
  "machine-shoulder-press": { alt: "Seated lifter holding shoulder-press machine handles beside the shoulders, then pressing upward.", secondPosition: "Pressed", setup: "Sit against the machine back pad and hold its handles at shoulder height.", movement: "Press the handles upward, then bring them back beside your shoulders slowly." },
  "dumbbell-lateral-raise": { alt: "Standing lifter holding dumbbells at the sides, then raising both arms sideways to shoulder level.", secondPosition: "Raised", setup: "Stand with a dumbbell in each hand at your sides and elbows softly bent.", movement: "Raise both arms out to the sides toward shoulder height, then lower them slowly." },
  "cable-lateral-raise": { alt: "Standing lifter holding a low cable handle across the body, then lifting that arm sideways.", secondPosition: "Raised", setup: "Stand side-on to a low cable and hold the handle with your outside hand across your body.", movement: "Lift that arm out to the side toward shoulder height, then lower it across your body." },
  "reverse-pec-deck": { alt: "Lifter facing a reverse pec-deck machine with arms forward, then opening them out to the sides.", secondPosition: "Open", setup: "Sit facing the machine chest pad and hold the reverse-fly handles in front of you.", movement: "Open your arms outward, then bring the handles forward under control." },
  "face-pull": { alt: "Standing lifter holding a high cable rope with arms forward, then pulling it toward the face with elbows wide.", secondPosition: "Pulled", setup: "Face a high cable pulley and hold the rope ends with arms extended.", movement: "Pull the rope toward your face with elbows spreading outward, then extend your arms again." },

  "barbell-curl": { alt: "Standing lifter holding a barbell at the thighs, then curling it toward the chest.", secondPosition: "Raised", setup: "Stand upright with an underhand grip on the barbell and arms at your sides.", movement: "Bend your elbows to curl the bar upward, then lower it to your thighs slowly." },
  "incline-dumbbell-curl": { alt: "Lifter reclining on an incline bench with dumbbells hanging below the shoulders, then curling them upward.", secondPosition: "Raised", setup: "Lean back on an incline bench with a dumbbell in each hand and arms hanging down.", movement: "Curl the weights toward your shoulders, then let your arms extend slowly." },
  "preacher-curl": { alt: "Seated lifter with upper arms on a preacher pad holding a curl handle low, then raising it toward the shoulders.", secondPosition: "Raised", setup: "Sit at the preacher machine with your upper arms against its sloped pad and hands on the handle.", movement: "Curl the handle upward, then lower it while your upper arms remain on the pad." },
  "hammer-curl": { alt: "Standing lifter holding dumbbells with palms facing inward at the sides, then curling them upward.", secondPosition: "Raised", setup: "Stand with a dumbbell in each hand and palms facing your body.", movement: "Curl the dumbbells toward your shoulders without turning your wrists, then lower them." },
  "cable-curl": { alt: "Standing lifter holding a low cable bar near the thighs, then curling it toward the chest.", secondPosition: "Raised", setup: "Face a low cable pulley and hold its bar with palms up and arms near your sides.", movement: "Curl the bar toward your chest, then lower it until your arms extend again." },

  "cable-pushdown": { alt: "Standing lifter holding a high cable handle at chest height, then pushing it down until arms extend.", secondPosition: "Pushed down", setup: "Face a high cable with elbows close to your sides and hands on its handle.", movement: "Straighten your elbows to push the handle toward your thighs, then let it rise slowly." },
  "overhead-cable-extension": { alt: "Lifter facing away from a low cable with rope held behind the head, then extending the arms overhead.", secondPosition: "Extended", setup: "Face away from the cable and hold its rope behind your head with elbows bent overhead.", movement: "Straighten your elbows above you, then bend them to return the rope behind your head." },
  "ez-bar-skull-crusher": { alt: "Lifter lying on a flat bench holding an EZ bar near the forehead, then extending the arms to raise it above the chest.", secondPosition: "Extended", setup: "Lie on a bench and hold an EZ bar near your forehead with elbows bent.", movement: "Extend your elbows to raise the bar above your chest, then bend them to lower it again." },
  "close-grip-bench-press": { alt: "Lifter on a flat bench gripping a barbell near shoulder width at the chest, then pressing it above the shoulders.", secondPosition: "Pressed", setup: "Lie on a flat bench with feet planted and grip the bar around shoulder width near your chest.", movement: "Press the bar up with elbows near your sides, then lower it toward your chest." },
  "seated-dip-machine": { alt: "Seated lifter holding dip-machine handles beside the torso, then pushing them downward.", secondPosition: "Pushed down", setup: "Sit against the dip machine backrest with hands on the handles beside your torso.", movement: "Push the handles down until your arms extend, then let them rise with control." },

  "barbell-back-squat": { alt: "Lifter standing with a barbell across the upper back, then squatting with knees and hips bent.", secondPosition: "Lowered", setup: "Stand with the barbell across your upper back and feet set apart on the floor.", movement: "Bend your hips and knees to squat down, then stand back up with control." },
  "leg-press": { alt: "Seated lifter on a leg-press machine with knees bent and feet on the sled, then pushing the sled away.", secondPosition: "Pressed", setup: "Sit against the leg-press back pad with both feet on the sled platform.", movement: "Extend your knees to press the sled away, then bend them to bring it back slowly." },
  "hack-squat": { alt: "Lifter against a hack-squat sled back pad, feet on its platform, first near standing and then lowered with knees bent.", secondPosition: "Lowered", setup: "Stand on the hack-squat foot platform with your back against the sled pad and shoulders under its pads.", movement: "Bend your hips and knees to lower the sled along its rails, then extend them to rise with control." },
  "leg-extension": { alt: "Seated lifter at a leg-extension machine with shins behind a roller and knees bent, then straightening the legs.", secondPosition: "Extended", setup: "Sit against the machine backrest with the roller across the front of your lower legs.", movement: "Straighten your knees to raise the roller, then lower it by bending your knees." },
  "bulgarian-split-squat": { alt: "Lifter holding dumbbells with rear foot on a bench, first upright then lowering the front leg into a split squat.", secondPosition: "Lowered", setup: "Stand ahead of a bench with one foot behind you on it and a dumbbell in each hand.", movement: "Bend your front knee and hip to lower straight down, then push through the front foot to rise." },

  "romanian-deadlift": { alt: "Lifter standing with a barbell at the thighs, then hinging at the hips to lower it along the legs.", secondPosition: "Hinged", setup: "Stand with a barbell at your thighs, feet planted, and knees slightly bent.", movement: "Push your hips back to lower the bar along your legs, then extend your hips to stand." },
  "dumbbell-romanian-deadlift": { alt: "Lifter holding dumbbells at the thighs, then hinging at the hips to lower them beside the legs.", secondPosition: "Hinged", setup: "Stand with a dumbbell in each hand beside your thighs and knees slightly bent.", movement: "Hinge at your hips to lower the weights along your legs, then stand by extending your hips." },
  "lying-leg-curl": { alt: "Lifter lying face down on a leg-curl machine with legs extended under an ankle roller, then bending the knees.", secondPosition: "Curled", setup: "Lie face down on the machine with its roller resting behind your ankles.", movement: "Bend your knees to draw your heels toward you, then extend your legs slowly." },
  "seated-leg-curl": { alt: "Lifter seated at a leg-curl machine with legs extended over an ankle roller, then bending knees downward.", secondPosition: "Curled", setup: "Sit against the back pad with thighs secured and the ankle roller behind your lower legs.", movement: "Bend your knees to pull the roller down and back, then let your legs extend." },

  "barbell-hip-thrust": { alt: "Lifter with upper back on a bench and barbell across hips, first hips lowered then raised in line with torso.", secondPosition: "Raised", setup: "Rest your upper back on a bench with a padded barbell across your hips and feet planted.", movement: "Extend your hips to lift the bar, then lower your hips toward the floor." },
  "dumbbell-walking-lunge": { alt: "Lifter holding dumbbells at the sides, first standing and then stepping forward into a lunge.", secondPosition: "Lowered", setup: "Stand tall holding a dumbbell in each hand at your sides.", movement: "Step forward and bend both knees into a lunge, then rise and step through with the other leg." },
  "cable-glute-kickback": { alt: "Lifter facing a low cable with an ankle cuff, first standing then moving the cuffed leg backward.", secondPosition: "Extended", setup: "Attach a low cable cuff to one ankle and face the machine while holding its support.", movement: "Move the cuffed leg backward at the hip, then bring it forward under control." },
  "hip-abduction-machine": { alt: "Seated lifter at a hip-abduction machine with knees together against pads, then pressing the knees outward.", secondPosition: "Opened", setup: "Sit against the machine back pad with the outer sides of your knees against its pads.", movement: "Press your knees outward against the pads, then let them return inward slowly." },

  "standing-calf-raise": { alt: "Standing lifter under calf-raise machine shoulder pads with heels low, then rising onto the balls of the feet.", secondPosition: "Raised", setup: "Stand on the machine platform with shoulders under its pads and balls of your feet supported.", movement: "Rise onto your toes by lifting your heels, then lower your heels slowly." },
  "seated-calf-raise": { alt: "Seated lifter under calf-raise thigh pads with heels lowered, then lifting heels while seated.", secondPosition: "Raised", setup: "Sit with your thighs under the machine pads and balls of your feet on its platform.", movement: "Lift your heels while your knees stay bent, then lower them slowly." },
  "leg-press-calf-raise": { alt: "Lifter seated at a leg press with balls of the feet on the sled, first ankles flexed then pushing through toes.", secondPosition: "Raised", setup: "Sit in the leg press with your knees nearly extended and balls of your feet on the platform.", movement: "Push the platform away by pointing your toes, then let your heels lower with control." },

  "cable-crunch": { alt: "Kneeling lifter holding an overhead cable rope beside the head, then curling the torso down toward the knees.", secondPosition: "Crunched", setup: "Kneel facing a high cable and hold the rope ends beside your head.", movement: "Curl your torso toward your knees, then uncurl slowly while keeping the rope near your head." },
  "machine-crunch": { alt: "Seated lifter in an abdominal-crunch machine first upright, then curling the torso forward against its pads.", secondPosition: "Crunched", setup: "Sit in the crunch machine with its pads or handles positioned against your upper body.", movement: "Curl your torso forward against the resistance, then return to upright with control." },
  "cable-woodchopper": { alt: "Standing lifter holding a high cable handle beside one shoulder, then drawing it diagonally across the torso.", secondPosition: "Chopped", setup: "Stand side-on to a high cable and hold the handle with both hands near the pulley-side shoulder.", movement: "Pull the handle diagonally across your body toward the opposite hip, then reverse the path slowly." },
};

export function exerciseDemoSrc(id: ExerciseId): string {
  return `/exercise-demos/${id}.webp`;
}
